# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vt-wishlist-app"
client_id = "46d60d2e35f97b8bd4fd586a44edc30d"
application_url = "https://berkeley-grow-invisible-herald.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://berkeley-grow-invisible-herald.trycloudflare.com/auth/callback",
  "https://berkeley-grow-invisible-herald.trycloudflare.com/auth/shopify/callback",
  "https://berkeley-grow-invisible-herald.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://berkeley-grow-invisible-herald.trycloudflare.com"
subpath = "wish"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vt-shopi-demo-store.myshopify.com"
